### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [bobrowskibiz/rep-kodilla#1]
- [x] zaciagnij zmiany
- [x] domerguj lokalnie brancha `test` do `brancha` master
- [x] wyslij zaktualizowany kod na branchu `master` na githuba

**Comment by bobrowskibiz** [comment]
1 zaciągniete za pomocą
$ git pull
2. domergowane w (master)  za pomocą
$ git merge test
3. odesłane za pomocą
$ git push origin master
